version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: delivery-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deliverydb
      MYSQL_USER: delivery
      MYSQL_PASSWORD: delivery123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: delivery-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/deliverydb
      SPRING_DATASOURCE_USERNAME: delivery
      SPRING_DATASOURCE_PASSWORD: delivery123

volumes:
  mysql-data: